title: Suspicious Shim Database Patching Activity
id: bf344fea-d947-4ef4-9192-34d008315d3a
status: experimental
description: Detects installation of new shim databases that try to patch sections
  of known processes for potential process injection or persistence.
references:
- https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/pillowmint-fin7s-monkey-thief/
- https://www.fireeye.com/blog/threat-research/2017/05/fin7-shim-databases-persistence.html
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023/08/01
modified: 2023/12/06
tags:
- attack.persistence
- attack.t1546.011
logsource:
  category: registry_set
  product: windows
detection:
- selection:
  - and:
    - TargetObject|contains: \SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Custom\
    - or:
      - TargetObject|endswith: \csrss.exe
      - TargetObject|endswith: \dllhost.exe
      - TargetObject|endswith: \explorer.exe
      - TargetObject|endswith: \RuntimeBroker.exe
      - TargetObject|endswith: \services.exe
      - TargetObject|endswith: \sihost.exe
      - TargetObject|endswith: \svchost.exe
      - TargetObject|endswith: \taskhostw.exe
      - TargetObject|endswith: \winlogon.exe
      - TargetObject|endswith: \WmiPrvSe.exe
- condition: selection
falsepositives:
- Unknown
level: high
