title: Suspicious Remote AppX Package Locations
id: 8b48ad89-10d8-4382-a546-50588c410f0d
status: experimental
description: Detects an appx package added the pipeline of the "to be processed" packages
  which is downloaded from a suspicious domain
references:
- Internal Research
- https://www.sentinelone.com/labs/inside-malicious-windows-apps-for-malware-deployment/
- https://learn.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting
- https://news.sophos.com/en-us/2021/11/11/bazarloader-call-me-back-attack-abuses-windows-10-apps-mechanism/
author: Nasreddine Bencherchali (Nextron Systems)
date: 2023/01/11
modified: 2024/02/09
tags:
- attack.defense_evasion
logsource:
  product: windows
  service: appxdeployment-server
detection:
- selection:
  - and:
    - EventID|==: 854
    - or:
      - Path|contains: .githubusercontent.com
      - Path|contains: anonfiles.com
      - Path|contains: cdn.discordapp.com
      - Path|contains: cdn.discordapp.com/attachments/
      - Path|contains: ddns.net
      - Path|contains: dl.dropboxusercontent.com
      - Path|contains: ghostbin.co
      - Path|contains: glitch.me
      - Path|contains: gofile.io
      - Path|contains: hastebin.com
      - Path|contains: mediafire.com
      - Path|contains: mega.nz
      - Path|contains: onrender.com
      - Path|contains: paste.ee
      - Path|contains: pastebin.com
      - Path|contains: pastebin.pl
      - Path|contains: pastetext.net
      - Path|contains: privatlab.com
      - Path|contains: privatlab.net
      - Path|contains: send.exploit.in
      - Path|contains: sendspace.com
      - Path|contains: storage.googleapis.com
      - Path|contains: storjshare.io
      - Path|contains: supabase.co
      - Path|contains: temp.sh
      - Path|contains: transfer.sh
      - Path|contains: ufile.io
- condition: selection
falsepositives:
- Unknown
level: high
