title: Invoke-Obfuscation RUNDLL LAUNCHER - Security
id: f241cf1b-3a6b-4e1a-b4f9-133c00dd95ca
related:
- id: 11b52f18-aaec-4d60-9143-5dd8cc4706b9
  type: derived
status: test
description: Detects Obfuscated Powershell via RUNDLL LAUNCHER
references:
- https://github.com/SigmaHQ/sigma/issues/1009
author: Timur Zinniatullin, oscd.community
date: 2020/10/18
modified: 2022/11/29
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
logsource:
  product: windows
  service: security
  definition: The 'System Security Extension' audit subcategory need to be enabled
    to log the EID 4697
detection:
- and:
  - EventID|==: 4697
  - ServiceFileName|contains: rundll32.exe
  - ServiceFileName|contains: shell32.dll
  - ServiceFileName|contains: shellexec_rundll
  - ServiceFileName|contains: powershell
falsepositives:
- Unknown
level: medium
