title: Invoke-Obfuscation STDIN+ Launcher - Security
id: 0c718a5e-4284-4fb9-b4d9-b9a50b3a1974
related:
- id: 72862bf2-0eb1-11eb-adc1-0242ac120002
  type: derived
status: test
description: Detects Obfuscated use of stdin to execute PowerShell
references:
- https://github.com/SigmaHQ/sigma/issues/1009
author: Jonathan Cheong, oscd.community
date: 2020/10/15
modified: 2022/11/29
tags:
- attack.defense_evasion
- attack.t1027
- attack.execution
- attack.t1059.001
logsource:
  product: windows
  service: security
  definition: The 'System Security Extension' audit subcategory need to be enabled
    to log the EID 4697
detection:
- selection:
  - and:
    - EventID|==: 4697
    - ServiceFileName|contains: cmd
    - ServiceFileName|contains: powershell
- selection2:
  - and:
    - or:
      - ServiceFileName|contains: ${input}
      - ServiceFileName|contains: noexit
- selection3:
  - and:
    - or:
      - ServiceFileName|contains: ' /c '
      - ServiceFileName|contains: ' /r '
- condition: all of selection*
falsepositives:
- Unknown
level: high
